export const dutchAuction_abi = [
  {
    type: "function",
    name: "priceNow",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "START_PRICE",
    inputs: [],
    outputs: [{ name: "", type: "int64", internalType: "int64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "START_TIME",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "END_TIME",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MIN_TO_OPEN",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "buyLiquidity",
    inputs: [{ name: "_payAmount", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "refundTokens",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;
